apiVersion: v2
description: Identity Helm Chart for Kubernetes
name: identity
version: 8.0.20
type: application
icon: https://raw.githubusercontent.com/camunda-cloud/camunda-cloud-documentation/master/static/img/iam.png
annotations:
  artifacthub.io/changes: |
    - create identity sub chart
  artifacthub.io/containsSecurityUpdates: "false"
dependencies:
  - name: keycloak
    repository: "https://helm.camunda.io"
    version: 7.1.6
    condition: "keycloak.enabled"