kind: ConfigMap
metadata:
  name: {{ include "zeebe.fullname" . }}
  labels: {{- include "zeebe.labels.broker" . | nindent 4 }}
apiVersion: v1
data:
  broker-log4j2.xml: |
{{- if .Values.log4j2 }}
    {{ .Values.log4j2 | indent 4 | trim }}
{{- end }}
